/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Items117Builder {
    //the instance to build
    private Items117 items117;

    /**
     * Default constructor to initialize the instance
     */
    public Items117Builder() {
        items117 = new Items117();
    }

    public Items117Builder request(Request request) {
        items117.setRequest(request);
        return this;
    }

    public Items117Builder correctedQuery(CorrectedQuery correctedQuery) {
        items117.setCorrectedQuery(correctedQuery);
        return this;
    }

    public Items117Builder qid(String qid) {
        items117.setQid(qid);
        return this;
    }

    public Items117Builder engineQuery(String engineQuery) {
        items117.setEngineQuery(engineQuery);
        return this;
    }

    public Items117Builder totalResults(Integer totalResults) {
        items117.setTotalResults(totalResults);
        return this;
    }

    public Items117Builder totalPages(Integer totalPages) {
        items117.setTotalPages(totalPages);
        return this;
    }

    public Items117Builder moreSearchResultsUrl(String moreSearchResultsUrl) {
        items117.setMoreSearchResultsUrl(moreSearchResultsUrl);
        return this;
    }

    public Items117Builder searchResultsMap(SearchResultsMap searchResultsMap) {
        items117.setSearchResultsMap(searchResultsMap);
        return this;
    }

    public Items117Builder item(List<Item116> item) {
        items117.setItem(item);
        return this;
    }

    public Items117Builder searchBinSets(SearchBinSets searchBinSets) {
        items117.setSearchBinSets(searchBinSets);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Items117 build() {
        return items117;
    }
}