/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Item116Builder {
    //the instance to build
    private Item116 item116;

    /**
     * Default constructor to initialize the instance
     */
    public Item116Builder() {
        item116 = new Item116();
    }

    public Item116Builder aSIN(String aSIN) {
        item116.setASIN(aSIN);
        return this;
    }

    public Item116Builder parentASIN(String parentASIN) {
        item116.setParentASIN(parentASIN);
        return this;
    }

    public Item116Builder errors(Errors errors) {
        item116.setErrors(errors);
        return this;
    }

    public Item116Builder detailPageURL(String detailPageURL) {
        item116.setDetailPageURL(detailPageURL);
        return this;
    }

    public Item116Builder itemLinks(ItemLinks itemLinks) {
        item116.setItemLinks(itemLinks);
        return this;
    }

    public Item116Builder salesRank(String salesRank) {
        item116.setSalesRank(salesRank);
        return this;
    }

    public Item116Builder smallImage(Image smallImage) {
        item116.setSmallImage(smallImage);
        return this;
    }

    public Item116Builder mediumImage(Image mediumImage) {
        item116.setMediumImage(mediumImage);
        return this;
    }

    public Item116Builder largeImage(Image largeImage) {
        item116.setLargeImage(largeImage);
        return this;
    }

    public Item116Builder imageSets(List<ImageSets> imageSets) {
        item116.setImageSets(imageSets);
        return this;
    }

    public Item116Builder itemAttributes(ItemAttributes itemAttributes) {
        item116.setItemAttributes(itemAttributes);
        return this;
    }

    public Item116Builder variationAttributes(VariationAttributes variationAttributes) {
        item116.setVariationAttributes(variationAttributes);
        return this;
    }

    public Item116Builder relatedItems(List<RelatedItems> relatedItems) {
        item116.setRelatedItems(relatedItems);
        return this;
    }

    public Item116Builder collections(Collections collections) {
        item116.setCollections(collections);
        return this;
    }

    public Item116Builder subjects(Subjects subjects) {
        item116.setSubjects(subjects);
        return this;
    }

    public Item116Builder offerSummary(OfferSummary offerSummary) {
        item116.setOfferSummary(offerSummary);
        return this;
    }

    public Item116Builder offers(Offers offers) {
        item116.setOffers(offers);
        return this;
    }

    public Item116Builder rentalOffers(RentalOffers rentalOffers) {
        item116.setRentalOffers(rentalOffers);
        return this;
    }

    public Item116Builder variationSummary(VariationSummary variationSummary) {
        item116.setVariationSummary(variationSummary);
        return this;
    }

    public Item116Builder variations(Variations variations) {
        item116.setVariations(variations);
        return this;
    }

    public Item116Builder customerReviews(CustomerReviews customerReviews) {
        item116.setCustomerReviews(customerReviews);
        return this;
    }

    public Item116Builder editorialReviews(EditorialReviews editorialReviews) {
        item116.setEditorialReviews(editorialReviews);
        return this;
    }

    public Item116Builder similarProducts(SimilarProducts similarProducts) {
        item116.setSimilarProducts(similarProducts);
        return this;
    }

    public Item116Builder accessories(Accessories accessories) {
        item116.setAccessories(accessories);
        return this;
    }

    public Item116Builder tracks(Tracks tracks) {
        item116.setTracks(tracks);
        return this;
    }

    public Item116Builder browseNodes(BrowseNodes browseNodes) {
        item116.setBrowseNodes(browseNodes);
        return this;
    }

    public Item116Builder alternateVersions(AlternateVersions alternateVersions) {
        item116.setAlternateVersions(alternateVersions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item116 build() {
        return item116;
    }
}