/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Items29Builder {
    //the instance to build
    private Items29 items29;

    /**
     * Default constructor to initialize the instance
     */
    public Items29Builder() {
        items29 = new Items29();
    }

    public Items29Builder item(List<Item28> item) {
        items29.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Items29 build() {
        return items29;
    }
}