/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Item28Builder {
    //the instance to build
    private Item28 item28;

    /**
     * Default constructor to initialize the instance
     */
    public Item28Builder() {
        item28 = new Item28();
    }

    public Item28Builder action(ActionEnum action) {
        item28.setAction(action);
        return this;
    }

    public Item28Builder cartItemId(String cartItemId) {
        item28.setCartItemId(cartItemId);
        return this;
    }

    public Item28Builder quantity(Integer quantity) {
        item28.setQuantity(quantity);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item28 build() {
        return item28;
    }
}