/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Item148Builder {
    //the instance to build
    private Item148 item148;

    /**
     * Default constructor to initialize the instance
     */
    public Item148Builder() {
        item148 = new Item148();
    }

    public Item148Builder aSIN(String aSIN) {
        item148.setASIN(aSIN);
        return this;
    }

    public Item148Builder parentASIN(String parentASIN) {
        item148.setParentASIN(parentASIN);
        return this;
    }

    public Item148Builder errors(Errors errors) {
        item148.setErrors(errors);
        return this;
    }

    public Item148Builder detailPageURL(String detailPageURL) {
        item148.setDetailPageURL(detailPageURL);
        return this;
    }

    public Item148Builder itemLinks(ItemLinks itemLinks) {
        item148.setItemLinks(itemLinks);
        return this;
    }

    public Item148Builder salesRank(String salesRank) {
        item148.setSalesRank(salesRank);
        return this;
    }

    public Item148Builder smallImage(Image smallImage) {
        item148.setSmallImage(smallImage);
        return this;
    }

    public Item148Builder mediumImage(Image mediumImage) {
        item148.setMediumImage(mediumImage);
        return this;
    }

    public Item148Builder largeImage(Image largeImage) {
        item148.setLargeImage(largeImage);
        return this;
    }

    public Item148Builder imageSets(List<ImageSets> imageSets) {
        item148.setImageSets(imageSets);
        return this;
    }

    public Item148Builder itemAttributes(ItemAttributes itemAttributes) {
        item148.setItemAttributes(itemAttributes);
        return this;
    }

    public Item148Builder variationAttributes(VariationAttributes variationAttributes) {
        item148.setVariationAttributes(variationAttributes);
        return this;
    }

    public Item148Builder relatedItems(List<RelatedItems145> relatedItems) {
        item148.setRelatedItems(relatedItems);
        return this;
    }

    public Item148Builder collections(Collections collections) {
        item148.setCollections(collections);
        return this;
    }

    public Item148Builder subjects(Subjects subjects) {
        item148.setSubjects(subjects);
        return this;
    }

    public Item148Builder offerSummary(OfferSummary offerSummary) {
        item148.setOfferSummary(offerSummary);
        return this;
    }

    public Item148Builder offers(Offers offers) {
        item148.setOffers(offers);
        return this;
    }

    public Item148Builder rentalOffers(RentalOffers rentalOffers) {
        item148.setRentalOffers(rentalOffers);
        return this;
    }

    public Item148Builder variationSummary(VariationSummary variationSummary) {
        item148.setVariationSummary(variationSummary);
        return this;
    }

    public Item148Builder variations(Variations147 variations) {
        item148.setVariations(variations);
        return this;
    }

    public Item148Builder customerReviews(CustomerReviews customerReviews) {
        item148.setCustomerReviews(customerReviews);
        return this;
    }

    public Item148Builder editorialReviews(EditorialReviews editorialReviews) {
        item148.setEditorialReviews(editorialReviews);
        return this;
    }

    public Item148Builder similarProducts(SimilarProducts similarProducts) {
        item148.setSimilarProducts(similarProducts);
        return this;
    }

    public Item148Builder accessories(Accessories accessories) {
        item148.setAccessories(accessories);
        return this;
    }

    public Item148Builder tracks(Tracks tracks) {
        item148.setTracks(tracks);
        return this;
    }

    public Item148Builder browseNodes(BrowseNodes browseNodes) {
        item148.setBrowseNodes(browseNodes);
        return this;
    }

    public Item148Builder alternateVersions(AlternateVersions alternateVersions) {
        item148.setAlternateVersions(alternateVersions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item148 build() {
        return item148;
    }
}