/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class MetaData126Builder {
    //the instance to build
    private MetaData126 metaData126;

    /**
     * Default constructor to initialize the instance
     */
    public MetaData126Builder() {
        metaData126 = new MetaData126();
    }

    public MetaData126Builder keyValuePair(List<KeyValuePair> keyValuePair) {
        metaData126.setKeyValuePair(keyValuePair);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetaData126 build() {
        return metaData126;
    }
}