/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RelatedItem144Builder {
    //the instance to build
    private RelatedItem144 relatedItem144;

    /**
     * Default constructor to initialize the instance
     */
    public RelatedItem144Builder() {
        relatedItem144 = new RelatedItem144();
    }

    public RelatedItem144Builder item(Item116 item) {
        relatedItem144.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RelatedItem144 build() {
        return relatedItem144;
    }
}