/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RelatedItem144 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5439200175809018495L;
    private Item116 item;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Item")
    public Item116 getItem ( ) { 
        return this.item;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Item")
    public void setItem (Item116 value) { 
        this.item = value;
    }
 
}
 