/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Variations147Builder {
    //the instance to build
    private Variations147 variations147;

    /**
     * Default constructor to initialize the instance
     */
    public Variations147Builder() {
        variations147 = new Variations147();
    }

    public Variations147Builder totalVariations(Integer totalVariations) {
        variations147.setTotalVariations(totalVariations);
        return this;
    }

    public Variations147Builder totalVariationPages(Integer totalVariationPages) {
        variations147.setTotalVariationPages(totalVariationPages);
        return this;
    }

    public Variations147Builder variationDimensions(VariationDimensions variationDimensions) {
        variations147.setVariationDimensions(variationDimensions);
        return this;
    }

    public Variations147Builder item(List<Item116> item) {
        variations147.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Variations147 build() {
        return variations147;
    }
}